name: Update Music Manifest

on:
  # Trigger on new MP3 uploads
  push:
    paths:
      - '**.mp3'
      - '**.m4a'
      - '**.wav'
    branches:
      - main
  
  # Trigger Manually (The "Run Now" Button)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Manifest JSON
        run: |
          # Scans the ROOT folder for audio files
          python3 -c "import os, json; files = [{'filename': f} for f in sorted(os.listdir('.')) if f.lower().endswith(('.mp3', '.m4a', '.wav'))]; print(json.dumps(files, indent=2))" > music.json

      - name: Commit and Push Manifest
        run: |
          git config --global user.name 'Manifest Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add music.json
          # Only push if music.json actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update music.json" && git push)
